### PR TITLE
Fix max_line_length ClientSession argument

### LINKED ISSUE #1884: Error with Streamlit example
modal-http: internal server error: status Failure: TypeError("ClientSession.__init__() got an unexpected keyword argument 'max_line_size'")

### PR DESCRIPTION
**Pull request by ekzhang**
Closes #1884

## Changelog

- Fix an issue with `@web_server` decorator not working on image builder version 2023.12

### CODE REVIEW

**Comment by mwaskom** [comment]
Thanks for figuring this out!

**Comment by ekzhang** [comment]
Can merge this after CI is fixed, see #1898
